apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: cloudflare-token
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"   # apply this before apps
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system

  project: rke2-cluster
  config: main
  secrets:
    - CLOUDFLARE_API_TOKEN

  managedSecret:
    name: cloudflare-api-token-secret
    namespace: cert-manager
    type: Opaque
