apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: techtronics-wildcard
  namespace: kube-system
spec:
  secretName: techtronics-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.techtronics.top"
