apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arr-stack-ingress
  namespace: arr-stack
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: sonarr.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack-service
                port:
                  number: 8989
    - host: radarr.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack-service
                port:
                  number: 7878
    - host: jdownloader2.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack-service
                port:
                  number: 5800
    - host: lidarr.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack-service
                port:
                  number: 8686
    - host: wizarr.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack-service
                port:
                  number: 5690
    - host: jellyseerr.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack-service
                port:
                  number: 5055
