apiVersion: v1
kind: Service
metadata:
  name: tachidesk
  namespace: tachidesk
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: tachidesk
  ports:
    - name: web
      port: 4567
      targetPort: 4567