apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | quote }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: {{ .Values.name | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
