apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas-2-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - truenas-2.techtronics.top
  rules:
    - host: truenas-2.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: truenas-2-service
                port:
                  name: http