apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: jellyfin
  annotations:
    # Jellyfin uses websockets + long-lived streams
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

    nginx.ingress.kubernetes.io/proxy-buffering: "on"   # required "on" for limit-rate
    #nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/limit-rate-after: "10240" #10MB
    nginx.ingress.kubernetes.io/limit-rate: "3750" #30Mbps

spec:
  ingressClassName: nginx
  rules:
    - host: jellyfin.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
    - host: threadfin.techtronics.top
      http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 34400