apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "100g" # Allow large file uploads
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off" # Disable request buffering for better performance, avoids buffering huge uploads.
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - immich.techtronics.top
  rules:
    - host: immich.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-service
                port:
                  name: http