apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubuntu-server-1-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ubuntu-server-1.techtronics.top
  rules:
    - host: ubuntu-server-1.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ubuntu-server-1-service
                port:
                  name: http