apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.40-192.168.0.70
  - fda1:b2c3:d4e5:1::4000-fda1:b2c3:d4e5:1::40ff
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: strong-nodes-only
  namespace: metallb-system
spec:
  ipAddressPools:
  - lan-pool
  nodeSelectors:
  - matchLabels:
      metallb-announce: "true"